ボウリングのスコア計算プログラムを作成
udaikue/ruby-practices pull request #1
Opened 2021-02-13 11:11 UTC by udaikue

ボウリングのスコア計算・オブジェクト指向版です。
ご確認お願いします。

2021-02-13 13:20 UTC, kakutani requested changes
フレームがたくさんあってややこしいですね。同じような処理の繰り返しをまとめられないか、考えてみてください~!

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/lib/bowling.rb
> +p game.score
```suggestion
puts game.score
```

pは「主にデバッグ用」です。
https://rurema.clear-code.com/3.0.0/method/Kernel/m/p.html

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +    @frame11 = Frame.new(@input[20], @input[21])
似ているけれどちょっと違うコードになっていますね。繰り返し処理をまとめられないか、チャレンジしてみてください。

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +  def score
ここも繰り返しがたくさんありますね。まとめられないでしょうか?

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/test/bowling_test.rb
> +require './lib/bowling'
`require_relative`を使ってください。

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/test/bowling_test.rb
> +  def test_bowling
テストメソッドは、ケース単位で定義してみてください。

```ruby
def test_テストケースの説明1
  game = Game.new...
  asser_equal...
end

def test_テストケースの説明2
  game = Game.new...
  asser_equal...
end
...
```

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +    @shot1 = Shot.new(shot1_mark)
この繰り返しもまとめられないでしょうか?

2021-02-13 13:20 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +  def score
ここもまとめられそうですね。

2021-02-15 05:17 UTC, udaikue commented on 07.bowling_object/lib/bowling.rb
> +p game.score
そうでした...putsに修正しました。

2021-02-15 05:20 UTC, udaikue commented on 07.bowling_object/test/bowling_test.rb
> +  def test_bowling
修正しました。

また、以下の日報に書いた内容で、テスト実行の際にコマンドライン引数がなくてもいいようにするために、require_relativeのところを変更しました。

https://bootcamp.fjord.jp/reports/25184

2021-02-15 05:21 UTC, udaikue commented on 07.bowling_object/lib/game.rb
> +    @frame11 = Frame.new(@input[20], @input[21])
繰り返しを箇所をまとめてみました。再度ご確認お願いします！

2021-02-15 05:37 UTC, kakutani requested changes
`require_relative`は直接使っているものを読み込むようにしてください。

Railsなどのフレームワークでは独自の読み込み機構を用意していますが、Rubyのみで使う場合には使うものを明示的に読み込んでください。

なお、Rubyでは1クラス1ファイルという決まりはありません(そうしてもいいし、複数クラスを1つのファイルにまとめて書いてもよい)。そこはプログラマーの判断だったり、チームやツールの規約だったりします。

2021-02-15 05:37 UTC, kakutani commented on 07.bowling_object/test/bowling_test.rb
> +require_relative '../lib/frame'
このテストコードから直接使っているのは`game.rb`だけだと思うので、他は不要だと思います。

2021-02-15 05:37 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +
`Frame`や'Bonus`をここで直接使っているので、`require_relative` で読み込むようにしてください。

2021-02-15 05:37 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +
`Shot`を直接使っているので、`require_relative`で読み込むようにしてください。

2021-02-15 05:37 UTC, kakutani commented on 07.bowling_object/lib/bowling.rb
> +require_relative 'shot'
`Game`以外はここでは直接使っていないので、`require_relative`で読み込まないでください。

2021-02-15 05:37 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +
`Shot`を直接使っているので、`require_relative`で読み込むようにしてください。

2021-02-15 05:40 UTC, kakutani commented on 07.bowling_object/lib/shot.rb
> +
この空行は不要だと思います(意味の区切りではなさそう)。

2021-02-15 06:00 UTC, kakutani requested changes
`Bonus`の算出ロジック以外を見ました。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +    @input.each_slice(2).map do |frame|
`map`の結果を使っていないので、ここは `each` が適切です。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +    @frame_sum = 0
`@frame_sum` は「フレームの合計」になりますが、フレームの何の合計なのかがわかりづらかったです。たとえば、「10」もフレームの合計になりえますよね(フレーム数の合計)。

`score`が全体のスコアなのだとすると、`subtotal`とか、倒したピンの数(`pins`)とか、もう少し読み手にヒントが欲しいです。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +    shots.map do |shot|
ここも`map`の結果を使っていないので `each`ですね。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +    @shot_sum = 0
ここも「ショットの合計」は何を指すのか曖昧かなと思いました。
2や3もショットの合計になりえると思います(フレームごとのショット数の合計)

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +    @shot_sum
`Fram#score`で返しているものが`@shot_shum`という名前ですが、これは`shot_shum`というよりは「当該フレームのスコア」なのでは? と思いました。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    calc_strike_and_spare_bonus + calc_double_strike_bonus
今回では、`calc_` という接頭辞は無くても意味は通りそうです
`Bonus#score`は「ストライク・スペアのボーナスと連続ストライクのボーナスを足したもの」と表現できそうです。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +    @input = input.gsub('X', 'X0').chars
`@input` はこのメソッドでしか使っていなさそう(インスタンス変数じゃなくてもよさそう)。

2021-02-15 06:00 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +      @frame = Frame.new(frame)
`@frame` はこのメソッドでしか使っていなさそうですね。

2021-02-15 06:03 UTC, kakutani commented
`Shot#score`について。

`#score`は呼び出されるたびに、文字列`@mark`から変換されて`score`の値を作っています。

今回の課題では元の文字列を保持しておく必要はなさそうなので、`initialize`のなかで文字列から数値に変換してしまってもよさそうです(`Shot`の各インスタンスを生成時に一度だけ変換しておく)。

2021-02-15 06:20 UTC, kakutani reviewed
Bonusの算出のところをコメントしました。

2021-02-15 06:20 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    @input_ary = input_ary.map do |shot|
`@input_ary`はこのメソッドでしか使っていないですね(ローカル変数でよい)。

2021-02-15 06:20 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      @shot = Shot.new(shot)
`@shot`はこのブロックでしか使っていませんね。

2021-02-15 06:20 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    @input_ary.each_slice(2) do |frame|
2つずつ区切った配列にしたいだけであれば、 `each_slice(2).to_a` でもいいかも(試さずに言ってます)。

2021-02-15 06:20 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      @strike_and_spare_bonus += (@score_ary[i - 1][0] != 10 ? frame[0] : frame.sum) if @score_ary[i - 1].sum == 10 && ((i != 0) && (i != 10) && (i != 11))
三項演算子に後置`if`も加わって、読むのがむずかしいです。
1行で短く書けているかもしれませんが、読むぶんには複雑です。

1行でなくてもよいし、プライベートメソッドに括り出すなどしてもらっても構わないので、整理してもらえると読みやすいです。

2021-02-15 06:20 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      @double_strike_bonus += frame[0] if (@score_ary[i - 2][0] == 10 && @score_ary[i - 1][0] == 10) && ((i != 0) && (i != 1) && (i != 11))
ここも後置ifの条件がたくさんあって、どういうことなのかを読み解くのがむずかしいです。

たとえば「0でなく1でなく11でもない」…どういうこと? と考えないといけなくて、認知負荷が高いです。

2021-02-15 11:25 UTC, udaikue commented on 07.bowling_object/lib/shot.rb
> +
`return`行の後ですよね？空行がないとrubocopで

```
Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
```

と言われるのでいれていました。

2021-02-15 11:45 UTC, kakutani commented on 07.bowling_object/lib/shot.rb
> +
なるほどRuboCopか…。ある程度、分量のロジックであれば、GuardClause(ガード節)とメソッド本体の処理の間に空行を入れることに意味はあります(意味の区切りなので)。ですが、このメソッドの現状でいえば:

```ruby
def score
  @mark == 'X' ? 10 : @mark.to_i
end
```

が適切だと思います。

2021-02-15 11:47 UTC, kakutani commented on 07.bowling_object/lib/shot.rb
> +
(さらにいうと、この計算は1回すれば良いだけなので、`#score`の呼び出しのたびに実施する必要はなく、インスタンスが生成されたときに一度だけでよさそうです(他の箇所でコメントした気がしますが…)。ここでは計算結果の`@score`だけ返せばよさそう。

2021-02-15 12:07 UTC, udaikue commented on 07.bowling_object/lib/shot.rb
> +
ありがとうございます！rubocop関係なしに1行で書けましたね。。

他の箇所でコメント頂いた件とあわせて修正します！

2021-02-16 01:26 UTC, udaikue commented on 07.bowling_object/lib/bonus.rb
> +    @input_ary.each_slice(2) do |frame|
`to_a`でうまくいったので変更しました！

2021-02-16 01:30 UTC, udaikue commented on 07.bowling_object/lib/bonus.rb
> +      @double_strike_bonus += frame[0] if (@score_ary[i - 2][0] == 10 && @score_ary[i - 1][0] == 10) && ((i != 0) && (i != 1) && (i != 11))
スペア、ストライク、連続ストライクを判定する部分をprivateメソッドにして修正してみました。いかがでしょうか...

> 「0でなく1でなく11でもない」

この部分はnextとbreakが使えることに気づいたので変更しました。

2021-02-16 02:28 UTC, kakutani reviewed
コードがすっきりしてくると、概念の統一性やクラスへの責務の配分が気になってきました。

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      shot.mark
ここは1行でよさそう(`shot`がなくてもわかりやすい)

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      @strike_and_spare_bonus += frame.sum if strike(i)
`strike?(i)` がよさそうです。

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      @strike_and_spare_bonus += frame[0] if spare(i)
`spare?(i)` がよさそうです

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      @double_strike_bonus += frame[0] if double_strike(i)
`double_strike?(i)` がよさそうです

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/bowling.rb
> +puts game.score
これぐらいなら`game`はインライン化して `Game.new(input).score` でよさそうです。

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +      @pins_per_frame += shot.mark
`Shot.new(mark).mark` でよさそう。

用語が shot, mark, pins と色々出てきているので、整理するとすっきりしそうな気がします。

* markは数字やXの文字列
* pinsは倒したピンの数
* Shotは投球
* scoreは…合計値だったりピンの数だったりしている

いずれにしても、'Shot#mark`で数値が取れるのは、概念の扱いが揺れていそうです。

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +      @pins_all_frame += frame.score
* `frame`はインライン化できそう
* `each`した合計値が欲しいなら、`#sum`が使えるかもしれません

https://rurema.clear-code.com/3.0.0/method/Array/i/sum.html

2021-02-16 02:28 UTC, kakutani commented on 07.bowling_object/lib/game.rb
> +    @pins_all_frame + @bonus.strike_and_spare_bonus + @bonus.double_strike_bonus
ゲームのスコアは「倒した全ピン数 + ボーナス点を加算したもの」という意図でもよさそうです(ボーナス点の具体的な算出方法は`Bonus`が知っていればよく、`Game`は知らなくてもよい)。

```ruby
def score
  @pins_all_frame + @bonus.score_subtotal
end
```

「ボーナススコア」をどのように算出するのかを、`Bonus`の責務とすれば、詳細はBonusだけが知っていればよい(個別のメソッドは`private`にしてよい)。
(メソッド名はテキトウです)

2021-02-16 06:52 UTC, udaikue commented on 07.bowling_object/lib/bonus.rb
> +      shot.mark
newのあとにつなげるのはダメだと勝手に思っていました💦

2021-02-16 06:55 UTC, udaikue commented on 07.bowling_object/lib/game.rb
> +    @pins_all_frame + @bonus.strike_and_spare_bonus + @bonus.double_strike_bonus
確かにGameのscoreでボーナスを足すのはよろしくないですね。。修正しました！

2021-02-16 06:57 UTC, udaikue commented on 07.bowling_object/lib/frame.rb
> +      @pins_per_frame += shot.mark
考え直してみました。これでいいのか悩ましいですが...

markはXなどの文字列、pinsは数値でわけたつもりです。

2021-02-16 15:04 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +      shot.mark
たしかに見た目がイマイチなのですが、ダメということはありません!

2021-02-16 15:08 UTC, kakutani commented on 07.bowling_object/lib/shot.rb
> +    @mark = mark
`@mark` は不要だと思います。

2021-02-16 15:09 UTC, kakutani commented on 07.bowling_object/lib/shot.rb
> +      @mark == 'X' ? 10 : @mark.to_i
この三項演算子は改行しなくてよいです。

2021-02-16 15:15 UTC, kakutani commented
PRでのコメントが長くなってきたので、[outdated] がついているところは、"Resolve Conversation"で解決済みにしてもらえると多少見やすくなるかもしれません!

2021-02-16 15:46 UTC, kakutani requested changes

2021-02-16 15:46 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    @score_ary.each_with_index do |frame, i|
`.each_with_index.sum` を使うと、`strike_and_spare_bonus`変数を使わずに値を算出できそうです。

2021-02-16 15:46 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    @score_ary.each_with_index do |frame, i|
ここも `#sum` を使うとローカル変数`double_strike_bonus`は取り除けそうです。

2021-02-16 15:57 UTC, kakutani commented
> markはXなどの文字列、pinsは数値でわけたつもりです。

この前提で読んでいくと、名前はもう少し整理できそうだなと思いました
(レビューコメントをつけようかと思ったのですが、細かすぎたのでやめておきます…)。

eachしている配列やコレクションの名前と、ブロックパラメータ名の関係が少しちぐはぐになっている感じでした。

例: `@score_ary`をeachしている要素の名前が`frame` ← ということは `@score_ary`というか`@frames`では?

コード中の、pins(これは数値だという前提で読んでいました)と、`Shot`と`score`の違いの受け止めがむずかしかったです。
`Shot`は投球なんだろうけど、実質`pins`みたいなだなあ、`score`は合計かなあ(でも`score_ary`があるなあ)と、もう少し整理できそうに思えました。

これは余談ですが、倒したピンの数は、 pin = 5, pin = 10 でもいいかもしれないなあ、と思いながら読んでいました。

2021-02-17 02:10 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    input_ary = input.map do |mark|
`do...end`は手続きを並べるのに使うのがよいと思います。ここでは、ブロックを評価した値を`map`して配列にまとめているので、`input_ary = input.map { |mark| Shot.new(mark).pins }` のほうが意図に近いと思います。

そしてこのコードを見ると、「入力値の配列」ではなくて「倒したピン数の配列」ですね(`pins_ary`のほうが意図に近い)

2021-02-17 14:38 UTC, udaikue commented on 07.bowling_object/lib/bonus.rb
> +    @score_ary.each_with_index do |frame, i|
'.each_with_index.sum'とすると

```
nil can't be coerced into Integer (TypeError)
```

となってしまってindexなしの`.each.sum`のときのようにうまくいかないのですが...

2021-02-17 14:42 UTC, udaikue commented on 07.bowling_object/lib/bonus.rb
> +    input_ary = input.map do |mark|
> markはXなどの文字列、pinsは数値でわけたつもりです。

としていましたが、改めて考え直しました。

markは抹消して、数値化される前はpins、数値化されたものはshotとすることにしました。
total_scoreとしていたのも、ただのscoreに戻しました。どうでしょうか...

2021-02-17 15:17 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    @score_ary.each_with_index do |frame, i|
混乱させてしまってすみません。字面だけ見て「できるのでは?」と思ってコメントしていたのですが、けっこう変形しないとうまく動かなさそうでした。なので、動作としては現行で動いていますので、ここはこのままでokです。

2021-02-17 15:17 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    @score_ary.each_with_index do |frame, i|
ここも、混乱させてしまった。ごめんなさい(字面だけ見て「できるのでは?」と思ってしまった)。このままでokです。

2021-02-17 15:21 UTC, kakutani commented on 07.bowling_object/lib/frame.rb
> +      end
ここは

```suggestion
    @shots_per_frame = pins.sum { |pin| Shot.new(pin).shot }
```

でよさそうです。

2021-02-18 08:36 UTC, kakutani commented on 07.bowling_object/lib/bonus.rb
> +    input_ary = input.map do |mark|
よさそうです!

2021-02-18 08:37 UTC, kakutani commented
最後にひとつだけコメントしました! ここだけ対応してもらえればOKかなーと思ってます。よろしくお願いします!

2021-02-18 12:30 UTC, merged